addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"          % "1.0.13")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"         % "3.9.2")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"              % "2.0.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"         % "2.3.2")
addSbtPlugin("com.dwijnand"      % "sbt-travisci"         % "1.2.0")
